# Generated by Django 6.0.1 on 2026-03-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_add_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name_plural': 'Social Links'},
        ),
    ]
